#!/bin/sh

VPN_NAME="client"

status=$2
case $status in
    up|vpn-down)
        if ! nmcli connection show --active | grep "$VPN_NAME"; then
            nmcli connection up id "$VPN_NAME"
        fi
        ;;
    down)
        if [ "$DEVICE_IFACE" = "tun0" ]; then
            exit
        fi

        if nmcli connection show --active | grep "$VPN_NAME"; then
            nmcli connection down id "$VPN_NAME"
        fi
        ;;
esac
