#!/bin/bash

ARG=$2

case $1 in
    pulse)
        echo INTERVAL=${ARG:-3000} > ~/.config/kbd_pulse.conf
        systemctl --quiet --user stop kbd_lighttimeout
        systemctl --quiet --user restart kbd_pulse
        STATE="pulsing"
        ;;
    timeout)
        echo TIMEOUT=${ARG:-30} > ~/.config/kbd_lighttimeout.conf
        systemctl --quiet --user stop kbd_pulse
        systemctl --quiet --user restart kbd_lighttimeout
        kbacklight 2
        STATE="timeout"
        ;;
    manual)
        systemctl --quiet --user stop kbd_pulse
        systemctl --quiet --user stop kbd_lighttimeout
        kbacklight 0
        STATE="manual"
        ;;
    cycle)
        if systemctl --quiet --user is-active kbd_lighttimeout; then
            systemctl --quiet --user stop kbd_lighttimeout
            systemctl --quiet --user start kbd_pulse
            STATE="pulsing"
        elif systemctl --quiet --user is-active kbd_pulse; then
            systemctl --quiet --user stop kbd_pulse
            kbacklight 0
        STATE="manual"
        else
            systemctl --quiet --user start kbd_lighttimeout
            kbacklight 2
            STATE="timeout"
        fi
esac

KEYBOARD_IMG="/home/vk/.local/share/icons/blue/keyboard.png"
LAST=`cat /tmp/kbd-not-id`
ARGS="-t 2000 -r ${LAST:-"0"} -p"
ARGS+=" -h string:image_path:$KEYBOARD_IMG"
notify-send $ARGS "Keyboard" "$STATE" > /tmp/kbd-not-id
