#!/bin/bash
kbacklight 0
TOGGLE=no
if ! volume silent | grep muted; then
    volume silent toggle
    TOGGLE=yes
fi

# Copy a placeholder until the actual image is generated by lock_generator.bash
cp ~/.local/share/win10lock-template-res.png /tmp/lockscreen.png
sync /tmp/lockscreen.png

i3lock -n -i /tmp/lockscreen.png &
LOCK_PID="$!"
systemctl --user start lock_generator.service

(sleep 7; xset dpms force off)&
SCREENOFF_PID="$!"

wait "$LOCK_PID"
kill "$SCREENOFF_PID" 2> /dev/null
xset dpms force on
systemctl --user stop lock_generator.service

if [ $TOGGLE = "yes" ]; then
    volume silent toggle
fi
