#!/bin/bash
systemctl --user start lock_generator.service
kbacklight 0
TOGGLE=no
if ! volume silent | grep muted; then
    volume silent toggle
    TOGGLE=yes
fi

(sleep 7; xset dpms force off)&

# Copy a placeholder until the actual image is generated by lock_generator.bash
cp ~/.local/share/win10lock-template-res.png /tmp/lockscreen.png

i3lock -n -i /tmp/lockscreen.png

# This kills the background subshell. That turns off the screen.
kill $!
# If the background process goes off right as I unlock the screen, I need to
# manually turn it on.
xset dpms force on

systemctl --user stop lock_generator.service

if [ $TOGGLE = "yes" ]; then
    volume silent toggle
fi
